# Generated by Django 2.2.7 on 2020-02-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modifield_time',
            new_name='modified_time',
        ),
    ]
